name: adv_mit
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio
  - aom
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - blosc
  - bokeh
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - comm
  - contourpy
  - cramjam
  - cryptography
  - cycler
  - cytoolz
  - daal4py
  - dal
  - dask
  - dask-core
  - debugpy
  - decorator
  - defusedxml
  - distributed
  - entrypoints
  - executing
  - expat
  - fastparquet
  - ffmpeg
  - flit-core
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - fsspec
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - heapdict
  - icu
  - idna
  - imagecodecs
  - imageio
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jasper
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - jupyterlab_widgets
  - jxrlib
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev=4.33
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - liblapack
  - liblapacke
  - libllvm11
  - libllvm12
  - libllvm14
  - libnghttp2
  - libogg
  - libopencv
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - libzopfli
  - llvm-openmp
  - llvmlite
  - locket
  - lxml
  - lz4
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpi
  - mpich
  - msgpack-python
  - munkres
  - mysql-common
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numba
  - numexpr
  - numpy
  - numpy-base
  - opencv
  - openh264
  - openjpeg
  - openssl
  - p11-kit
  - packaging
  - pandas
  - pandocfilters
  - parso
  - partd
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - ply
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - py-opencv
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python=3.10.9
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytorch
  - pytz
  - pywavelets
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - requests
  - scikit-image
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - snappy
  - sniffio
  - sortedcontainers
  - soupsieve
  - sqlite
  - stack_data
  - svt-av1
  - tbb
  - tblib
  - terminado
  - threadpoolctl
  - tifffile
  - tinycss2
  - tk
  - toml
  - toolz
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - xz
  - yaml
  - zeromq
  - zfp
  - zict
  - zlib
  - zstd
  - pip:
    - pyqt5-sip==12.11.0
    - pyyaml==6.0
    - ruff==0.0.257
    - torchattacks==3.3.0
