name: adv_mit
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - jupyter
  - scipy
  - matplotlib
  - tqdm
  - numpy
  - scikit-learn
  - pip:
    - pyqt5-sip
    - pyyaml
    - ruff
    - torchattacks
